//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_3erParcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodega
    {
        public int BodegaID { get; set; }
        public Nullable<int> Id_producto { get; set; }
        public string Nombre_producto { get; set; }
        public string Nombre_proveedor { get; set; }
        public Nullable<int> Stock { get; set; }
    }
}
