//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_3erParcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int ReporteID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public string Status_producto { get; set; }
        public Nullable<int> ProveedorID { get; set; }
        public string Status_proveedor { get; set; }
    }
}
